"""Add settings model

Revision ID: 09b3340bff65
Revises: 6590e6e45137
Create Date: 2024-06-01 12:49:58.244654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b3340bff65'
down_revision = '6590e6e45137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('webhooks', sa.JSON(), nullable=True),
                    sa.Column('received_hooks', sa.JSON(), nullable=True),
                    sa.Column('blocked_hooks', sa.Integer(), nullable=True),
                    sa.Column('domain', sa.String(length=255), nullable=True),
                    sa.Column('pump_webhook', sa.String(length=255), nullable=True),
                    sa.Column('dump_webhook', sa.String(length=255), nullable=True),
                    sa.Column('pump_data', sa.Text(), nullable=True),
                    sa.Column('dump_data', sa.Text(), nullable=True),
                    sa.Column('enable_pump', sa.Boolean(), nullable=True),
                    sa.Column('enable_dump', sa.Boolean(), nullable=True),
                    sa.Column('check_per_minutes_rapid', sa.Integer(), nullable=True),
                    sa.Column('check_per_minutes_smooth', sa.Integer(), nullable=True),
                    sa.Column('max_save_minutes', sa.Integer(), nullable=True),
                    sa.Column('price_change_percent', sa.Float(), nullable=True),
                    sa.Column('price_change_trigger_percent', sa.Float(), nullable=True),
                    sa.Column('oi_change_percent', sa.Float(), nullable=True),
                    sa.Column('cvd_change_percent', sa.Float(), nullable=True),
                    sa.Column('v_volumes_change_percent', sa.Float(), nullable=True),
                    sa.Column('use_spot', sa.Boolean(), nullable=True),
                    sa.Column('use_wicks', sa.Boolean(), nullable=True),
                    sa.Column('tg_users_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
