"""Primary back, but cycled

Revision ID: 1d81ac844e77
Revises: bee55857fe15
Create Date: 2024-06-20 23:48:34.335541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d81ac844e77'
down_revision = 'bee55857fe15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
