"""Add changes_log model

Revision ID: 1ee16b020db1
Revises: 09b3340bff65
Create Date: 2024-06-01 13:01:21.701001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee16b020db1'
down_revision = '09b3340bff65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('changes_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=True),
    sa.Column('change_amount', sa.String(length=10), nullable=True),
    sa.Column('interval', sa.Integer(), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('curr_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('changes_log')
    # ### end Alembic commands ###
