"""Add coins_blacklist and use_only_usdt columns

Revision ID: 24ece299d5e3
Revises: 5dda90ff1925
Create Date: 2024-06-10 13:53:41.917375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ece299d5e3'
down_revision = '5dda90ff1925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('use_only_usdt', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settings', sa.Column('coins_blacklist', sa.ARRAY(sa.String()), nullable=False, server_default=sa.text('ARRAY[]::VARCHAR[]')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'coins_blacklist')
    op.drop_column('settings', 'use_only_usdt')
    # ### end Alembic commands ###
