"""Change log autoinc

Revision ID: 8077f3970205
Revises: 8377d7323e56
Create Date: 2024-06-27 15:23:39.673980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8077f3970205'
down_revision = '8377d7323e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
