"""Comment

Revision ID: b85d87e46116
Revises: f8e1394997cf
Create Date: 2024-06-06 03:18:57.157646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b85d87e46116'
down_revision = 'f8e1394997cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('check_per_minutes_rapid', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('rapid_delay', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('rapid_pump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('rapid_dump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('rapid_pump_data', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('rapid_dump_data', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('rapid_enable_pump', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('rapid_enable_dump', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('check_per_minutes_smooth', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('smooth_delay', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('smooth_pump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('smooth_dump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('smooth_pump_data', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('smooth_dump_data', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('smooth_enable_pump', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('smooth_enable_dump', sa.Boolean(), nullable=True))
    op.drop_column('settings', 'pump_data')
    op.drop_column('settings', 'enable_dump')
    op.drop_column('settings', 'check_per_minutes_mode_2')
    op.drop_column('settings', 'pump_webhook')
    op.drop_column('settings', 'dump_data')
    op.drop_column('settings', 'dump_webhook')
    op.drop_column('settings', 'enable_pump')
    op.drop_column('settings', 'check_per_minutes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('check_per_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('enable_pump', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('dump_webhook', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('dump_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('pump_webhook', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('check_per_minutes_mode_2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('enable_dump', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('pump_data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('settings', 'smooth_enable_dump')
    op.drop_column('settings', 'smooth_enable_pump')
    op.drop_column('settings', 'smooth_dump_data')
    op.drop_column('settings', 'smooth_pump_data')
    op.drop_column('settings', 'smooth_dump_webhook')
    op.drop_column('settings', 'smooth_pump_webhook')
    op.drop_column('settings', 'smooth_delay')
    op.drop_column('settings', 'check_per_minutes_smooth')
    op.drop_column('settings', 'rapid_enable_dump')
    op.drop_column('settings', 'rapid_enable_pump')
    op.drop_column('settings', 'rapid_dump_data')
    op.drop_column('settings', 'rapid_pump_data')
    op.drop_column('settings', 'rapid_dump_webhook')
    op.drop_column('settings', 'rapid_pump_webhook')
    op.drop_column('settings', 'rapid_delay')
    op.drop_column('settings', 'check_per_minutes_rapid')
    # ### end Alembic commands ###
