"""Removed id from prices

Revision ID: bee55857fe15
Revises: e7d7053ebe99
Create Date: 2024-06-20 23:36:27.668803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bee55857fe15'
down_revision = 'e7d7053ebe99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
