"""Added reversal webhooks

Revision ID: df9ff51c27f9
Revises: 8077f3970205
Create Date: 2024-07-11 17:23:07.346729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9ff51c27f9'
down_revision = '8077f3970205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('reverse_rapid_pump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('reverse_rapid_dump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('reverse_smooth_pump_webhook', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('reverse_smooth_dump_webhook', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'reverse_smooth_dump_webhook')
    op.drop_column('settings', 'reverse_smooth_pump_webhook')
    op.drop_column('settings', 'reverse_rapid_dump_webhook')
    op.drop_column('settings', 'reverse_rapid_pump_webhook')
    # ### end Alembic commands ###
